ansible_become_pass: ENC[AES256_GCM,data:o/WyEKj6,iv:BfCdNy5LQIa0Ia1fBoeiX/Er7xzEJeqNw3LN62JE5Mo=,tag:/E+YqmFVQar192IGYQiHjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l9u8jjefsvmsy4887l79u6wqhzg3dw5q8g8ge8jz8mjlea4fcunsqe8fvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByckIwYVFUWU8xMS9tQTNE
            NFNwR05EaHg0cFRtaFprWVdTQ2xYMTQyMHp3CjVkTElueGJuWlFUTnQ0SjFPcXB5
            MzNIUUVHYXhKYTNsOS9HVTU2bmdDT2MKLS0tIHFpUzVGWjFNa1JQK2xCWmdKK3or
            QzhpZlpCYXFLYWJRbEZXQ2x0SEs0M1UKB7oMpUs35LZdk0OW1BBS7GRN3NtczxA1
            KfHTZ60wA0g9LyOMbZE7X7q7+aTcFnK2ST4JJvuLhtYlqzCJ240/LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T20:33:22Z"
    mac: ENC[AES256_GCM,data:W9o3mI8SxXM1RlLWIkLbp1EJQzqAbCHzehirXWrvzrqmuKAhanE5EcUA9matbP1mncwTlKG4ZSbHtQsgoJZqvLPlXIiRa5JCLayiH5SxLarBW2pO7kPlUrHhK5P7XfP7DbQHWkDf+WUzzM6bIUKcEc9mgVbNzt7YSZRszSorQC4=,iv:mrnuse1jkm9l7vNhL6Y07jxPv+EPemJ9p24/VTOffSA=,tag:zf/NjU3hXlOwDYs9JfvXJw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
