apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Tt9jqRhqOL6n4mm5GWSLIfeH0oi4a93WDGkUmMDaWgxyeW3ZM8s93g==,iv:UErcyTiHNv5k1nYTFeXu7iMQvkjhG4sRvQoELR2M9J4=,tag:wYcR5CguWRhtevRcI0hTTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l9u8jjefsvmsy4887l79u6wqhzg3dw5q8g8ge8jz8mjlea4fcunsqe8fvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaS092djlRSXdjUHYzQlR5
            ZDQ4QUZNRVpYd2VDaGs1NFJNS1BXRU5HRmhzCitibkV5WTlVQktJU0R0V3VhVDFO
            Qys1R1FqZnVTcloyOFQrS202WlZxUjQKLS0tIGM4SS9TN2htaitlWGxCWVRkSEVM
            eWNJZ1lidzgzL2F5UWV0am8yVmxpZzQKhVh7SE0N8n1/XMH3k80QRIOYU5pokEL4
            4Pwoa8HepUQsn8HJ47RiCNCY3MySit32e088eCBsbRKCfm9SHJGu6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T16:43:29Z"
    mac: ENC[AES256_GCM,data:OcI9QcSdUBRhEjVShlFSIUPSMIuj+bVw3Hl5DCq/biXI1LujJY5nnaErfHd+KH8+LesWE14VMQEefLNNrZiFoS4HhLCAWpQn7a7pH2U4iSXgsvskUAIilksbZF6f6Y7pFFGQsuHAGyqqNbj1Has1MeW807iZt+ZZsOq7i03OBdM=,iv:4FR4nigeF+MT/e27kzW5gu+ZJQSM7y8Lq2Fm7YPNNuU=,tag:1Z20JKIyGpC5t9ZfwHeIvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
