apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:CnbHonLOkxZ9z3p3,iv:PCWHq2UAKbavuF9Qj5mhDrB90wLkixGLVDCKseqJlww=,tag:/I51UcEmzMvaCYvzG+uT0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l9u8jjefsvmsy4887l79u6wqhzg3dw5q8g8ge8jz8mjlea4fcunsqe8fvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVXhyS1lBSFh5dzlRLzFP
            TXZwMGxtVkdBd1RlMis3bzR1aWpqNEpFdTJVCitrWjJFVXMyY3lORDM3bmJpSWRp
            Z0tKVEZsT1VRS3dKdVNGcWZobHpYK3cKLS0tIGtieS9jMWFGd1pKeVdBZGlMQ2o3
            SVloZU5ZdG9FWnk1TktCTEYzWlJSRmcK98Ko4BfAateOR5+EltEIeivx1bDI1lTo
            8spA6XPr7RxZJz8xNb7Pa/p9CVG0+kHQvYcn45oINI0/2cjUKA8d7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T16:43:30Z"
    mac: ENC[AES256_GCM,data:ugI25FAfJVqkB9odnx67Pj/zQZGTdQItvOs9iY1kyQu8VUYL1nQqDsadeWCbVF4zWVgaSqMcD/I5lTpsx6YdR7yM6W41MxUrYpkc4SDFja1LPdyYH2L02hJ83zXslRxuhzU4pTWozA+ho24h2Ti6gi/vSerP8RAn0odL4Q9FO4w=,iv:w/xBNkqT/04ySLqAQA1GxIn/LoVlvC3uiwxeFbR3LOw=,tag:fmdUk1u1XlVgIWv0YE6Prw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
