apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:uJUgIqWXJXsKnsrNdR1JrBEDxWKlUnmax5T07V8UwTxwCfvM,iv:2rcbSF+gcTlOHmnHFaPMlARVDiESiCYOgTZK36QxZJg=,tag:4gd4hB343cP3YRlJrTH41w==,type:str]
    credentials.json: ENC[AES256_GCM,data:jMLbu38QUazpVJ6N43KGjn9aE5P6un/BycvKmX67lBifVPX2LG6/6S7etGNfKeDFMS76jg/py23L0fHrB+SiNyJgnYK4ECVrHFixKareqy0XJPsWis0pt2dXUkek/BeaxMflzWqxziT+Ur4uOjnELOvk6W4IdcuiXPgtGyLC5+ygS99CNb0HnRZbdc83WzxUYmurplzY7F9UpVI9pJZhiy0UqL8+1kx0vPtYHpgDfw==,iv:6HmKpGnyH9gAX3dbObB6zhQx2fURVrEkIgcEXXHOpLQ=,tag:XJkevN2huuIUiY4gME2cYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l9u8jjefsvmsy4887l79u6wqhzg3dw5q8g8ge8jz8mjlea4fcunsqe8fvg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK3Y5bVRoUWpoTVpiN0V0
            K1pDMldWQlF0T28yOTVYaWNiclVvSkZMb3pnCnRFSEJDMGU4bFUzdVdaWm5QUkRz
            Ymd4djhPeG1UeTRkaWtqVE5xYTFodDgKLS0tIHNIeXl1cUloVStuRHptRkExNHA2
            T3BYOEl3M0t0Z2E5aXVJc2M0bHNyTlUKmhGAyPI1lTJCrOcixs/S+WO70U6CH3kP
            /CyXfRXBumS6y276Ll4t2uiyrL3muMuhmuQUkzSJ73H5MeFiHBicHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-30T16:43:28Z"
    mac: ENC[AES256_GCM,data:G8gHOcylT1Ie/ycfucq+PJpZXyNDAZMaAJ5EUBCv0uiGZ8XMrUoE04/l+JEVlLSmLZ4PNZeN8RoYzFcN8fW+2a3w+ZowO7/j3XPunVWRTpvHykzndCHCnT/9jmHdfm1AvoiXHHspWWRRjI1O45HoNPvg/N1Q9kjaGrwUGnYtW7w=,iv:gsaiA8vSq9IPdBUplymqrZfzoZXdgaWm1JcDnhyIsr0=,tag:WnfCoNx0ar0CW4e2v4hGwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
